import { IRoute } from "@bluelibs/x-ui";
import "./i18n";

import {
  ACTIVITY_LOG_DETAILS_LIST as BASE_ACTIVITY_LOG_DETAILS_LIST,
  ACTIVITY_LOG_DETAILS_CREATE as BASE_ACTIVITY_LOG_DETAILS_CREATE,
  ACTIVITY_LOG_DETAILS_EDIT as BASE_ACTIVITY_LOG_DETAILS_EDIT,
  ACTIVITY_LOG_DETAILS_VIEW as BASE_ACTIVITY_LOG_DETAILS_VIEW,
} from "./config/routes";

export const ACTIVITY_LOG_DETAILS_LIST: IRoute = {
  ...BASE_ACTIVITY_LOG_DETAILS_LIST,
};

export const ACTIVITY_LOG_DETAILS_CREATE: IRoute = {
  ...BASE_ACTIVITY_LOG_DETAILS_CREATE,
};

export const ACTIVITY_LOG_DETAILS_EDIT: IRoute = {
  ...BASE_ACTIVITY_LOG_DETAILS_EDIT,
};

export const ACTIVITY_LOG_DETAILS_VIEW: IRoute = {
  ...BASE_ACTIVITY_LOG_DETAILS_VIEW,
};
